general:
  num_workers: 8
  gpus: [0, 1, 2, 3]
flow:
  flownet2_dir: "/home/achald/research/misc/flow/flownet2"
tracker:
  visualize: False
model:
  joint:
    dir: "release/model/joint/"
    step: 4999
  objectness:
    dir: "release/model/objectness/"
    step: 89999
fbms:
  root: "/data/all/FBMS"
  splits: ['TestSet'] # ['TrainingSet', 'TestSet']
  images_highres:
    TestSet: "/data/all/FBMS/TestSet-highres"
    TrainingSet: "/data/all/FBMS/TrainingSet-highres"
  # Clone from https://github.com/achalddave/fbms-evaluation
  eval_dir: "/home/achald/research/misc/datasets/fbms/fbms-eval_fixed/evalcode/"
  output_dir: "release/outputs/fbms"
davis16:
  root: "/data/all/DAVIS/2016/"
  splits: ['val']  # 'train', 'val', or 'trainval'
  output_dir: "release/outputs/davis16"
davis17:
  root: "/data/all/DAVIS/2017/"
  splits: ['val_moving']  # 'val_moving', 'val', 'test', 'test-dev'
  output_dir: "release/outputs/davis17"
ytvos: "TODO"