general:
  num_workers: 8
  gpus: [0, 1, 2, 3]
flow:
  flownet2_dir: "/home/achald/research/misc/flow/flownet2"
tracker:
  visualize: False
fbms:
  root: "/data/all/FBMS"
  eval_dir: "/home/achald/research/misc/datasets/fbms/fbms-eval_fixed/evalcode/"
  images_highres:
    test: "/data/all/FBMS/TestSet-highres"
    train: "/data/all/FBMS/TrainingSet-highres"
  flow_dir: "/scratch/achald/debug_release/fbms/flownet2_out/"
  appearance_output: "/data/achald/track/detectron-pytorch/e2e_mask_rcnn_R-50-FPN_1x/objectness-Jul14-16-38-46_compute-1-16.local_step/step89999/infer-simple-fbms/outputs/"
  joint_output: "/data/achald/track/detectron-pytorch/e2e_mask_rcnn_R-50-FPN_1x_two_stream_adaptor_mask_rgb_only/davis16-instance-rgb+flownet2_freeze-rgb-flow-bodies-mask-head-outs_from-ytvos-strict-1076f32b_from-objectness-and-ft3dNov02-19-52-31/step4999/infer-simple-fbms/outputs/"
  track_output: "/scratch/achald/debug_release/fbms/fbms_output/"
davis: "TODO"
ytvos: "TODO"