general:
  num_workers: 8
  gpus: [0, 1, 2, 3]
flow:
  flownet2_dir: "/path/to/flownet2/repo"  # ***EDIT THIS***
tracker:
  visualize: False
model:
  joint:
    dir: "release/model/joint/"
    step: 4999
  joint_no_ytvos:
    dir: "release/model/joint_no_ytvos"
    step: 1999
  appearance:
    dir: "release/model/appearance/"
    step: 89999
  motion:
    dir: "release/model/motion/"
    step: 9999
fbms:
  root: "/path/to/FBMS/data/"  # ***EDIT THIS***
  splits: ['TestSet'] # ['TrainingSet', 'TestSet']
  images_highres:
    TestSet: "/path/to/FBMS-TestSet-highres-images"  # ***EDIT THIS***
    TrainingSet: "/path/to/FBMS-TrainingSet-highres-images"  # ***EDIT THIS***
  # Clone from https://github.com/achalddave/fbms-evaluation
  eval_dir: "/path/to/fbms-evaluation-code/"  # ***EDIT THIS***
  output_dir: "release/outputs/fbms"
davis16:
  # Contains subdirectories 'Annotations', 'JPEGImages', 'ImageSets'
  root: "/path/to/DAVIS/2016/data"  # ***EDIT THIS***
  splits: ['val']  # 'train', 'val', or 'trainval'
  output_dir: "release/outputs/davis16"
davis17:
  # Contains subdirectories 'Annotations', 'JPEGImages', 'ImageSets'
  root: "/path/to/DAVIS/2017/data"  # ***EDIT THIS***
  splits: ['moving_val']  # 'moving_val', 'val', 'test', 'test-dev'
  output_dir: "release/outputs/davis17"
ytvos:
  # Contains subdirectories 'train', 'train_all_frames'
  #   Each subdirectory should contain 'Annotations' and 'JPEGImages'
  #   subdirectories.
  root: "/path/to/ytvos/data"  # ***EDIT THIS***
  # 'moving_val', 'moving_train', 'train', 'valid', 'test'
  splits: ['moving_val']
  output_dir: "release/outputs/ytvos"
  # TODO: Use joint model without YTVOS here.